
server:
  port: 8001
spring:
  application:
    name: PLAT-SERVICE  #服务的名字
  profiles: dev #开发环境
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka  #服务注册的注册中心的地址
---
server:
  port: 8004
spring:
  application:
    name:  PLAT-SERVICE-TEST  #服务的名字
  profiles: test #开发环境
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka  #服务注册的注册中心的地址
